version: '3.7'

services:
  web:
    build:
         context: ./app 
         dockerfile: Dockerfile
    #command: "python manage.py runserver_plus --cert-file cert/server.cert --key-file cert/server.key 0.0.0.0:8000"
    volumes:
      - ./app/:/opt/app/
    ports:
      - 443:8000
    env_file:
      - ./env/django.env
